# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5a1dabfe859c3d699321d1b6194dcdad7286755662c45e6769fb343fbac427b2a499b1966f68dbf97145c7761120add6bbbfa744c10c9eb2ca7e1f1fe5840c0

test:
  secret_key_base: cea9aee597d7ef34902a1334d073a60ab53a4730adc579a8b28a435fdc88748d08fcdebb518e74e404f6d3f4b1f255379ab5cafaee2c12db702a1552ceb0b537

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
